# Generated by Django 4.2.1 on 2023-05-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
