# Generated by Django 4.2.1 on 2023-05-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopUser', '0003_customuser_is_admin_customuser_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
    ]
