# Generated by Django 4.2.1 on 2023-05-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0003_alter_sales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
