# Generated by Django 4.2.1 on 2023-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sell', '0005_alter_sales_id_alter_sales_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
